name: C

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and run tests
        run: |
          gcc c/test.c c/u64_dyn.c -o c/test
          ./c/test
