name: C

on:
  push:
    branches:
      - senpai
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install formatter
        run: sudo apt-get update && sudo apt-get install -y clang-format
      - name: Check formatting
        working-directory: c
        run: |
          clang-format -i *.c *.h
          git diff --exit-code
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        working-directory: c
        run: gcc test.c u64_dyn.c -o test
      - name: Run tests
        working-directory: c
        run: ./test
