name: C

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        working-directory: c
        run: |
          clang-format -i *.c *.h
          git diff --exit-code
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        working-directory: c
        run: gcc test.c u64_dyn.c -o test
      - name: Run tests
        working-directory: c
        run: ./test
  test-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        working-directory: c
        run: gcc test.c u64_dyn.c -o test -march=native
      - name: Run tests
        working-directory: c
        run: ./test
