name: C++

on:
  push:
    branches:
      - senpai
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        working-directory: cpp
        run: |
          clang-format -i *.cpp *.hpp
          git diff --exit-code
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        working-directory: cpp
        run: g++ -std=c++17 test.cpp -o test
      - name: Run tests
        working-directory: cpp
        run: ./test
