name: JavaScript

on:
  push:
    branches:
      - senpai
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        working-directory: js
        run: |
          npm install
          npm run prettier
          git diff --exit-code
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        working-directory: js
        run: npm test
