name: Lua

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: debian-10
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        working-directory: lua
        run: lua test.lua
