name: PHP

on:
  push:
    branches:
      - senpai
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        working-directory: php
        run: php test.php
